/*
 * Question History Table Update Script
 * This script recreates the question history table with updated structure
 * 
 * Purpose:
 * - Stores a record of all questions generated by users
 * - Links questions to specific users through user_id
 * - Maintains timestamps for tracking usage
 *
 * Fields:
 * - id: Unique identifier for each question set
 * - user_id: Foreign key to userinfo table
 * - input_text: Original text provided by user
 * - generated_questions: Questions created from the input
 * - created_at: When the questions were generated
 */

-- Drop existing table if it exists
DROP TABLE IF EXISTS question_history;

-- Create the table with user_id field
CREATE TABLE question_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    input_text TEXT NOT NULL,
    generated_questions TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES userinfo(id)
); 